### ISSUE TITLE
Ya no funciona

### ISSUE THREAD

**Issue by AlexisPradoLucero** [Theblood/Celuzador#1]
No esta funcionando

**Comment by Theblood** [comment]
Hola @AlexisPradoLucero , gracias por reportar, tuvimos un bloqueo de WhatsApp esto hizo que nuestro vps reintentará obtener la información por lo que se comenzó a colapsar a eso de las 17:00 recibí un mensaje de estábamos al 100% de recursos por lo que nos pusimos a trabajar y ahora está devuelta nuevamente la fuente principal y prontamente WhatsApp 🥂
