### ISSUE TITLE
Es posible buscar por nombre

### ISSUE THREAD

**Issue by danieldumma** [Theblood/Celuzador#2]
Seria bueno que se pudiera buscar por nombre

**Comment by Theblood** [comment]
Hola @danieldumma estamos trabajando para aquello, tambien trabajamos para integrar nuevas fuentes como telegram y facebook

**Comment by danieldumma** [comment]
Vale muchas gracias quisiera reportar un bug ya no aparece el nombre completo antes si aparecia incluso aparece el segundo apellido ejemplo antes aparecia nombre segundo nombre apellido segundo apellido ahora aparece nombre segundo apellido espero que lo solucione

**Comment by Theblood** [comment]
@danieldumma  por cosas de etica/legal tuvimos que enmascarar nombres, lo sentimos pero esto no es parte de un bug, sin embargo agregamos mas informacion a la api.

**Comment by danieldumma** [comment]
Entonces ya no vale la pena tan buena pagina que era
