### ISSUE TITLE
Ya no esta funcionando

### ISSUE THREAD

**Issue by AlexisPradoLucero** [Theblood/Celuzador#3]
Hola queria mirar la pagina y tambien probe la api ya no esta funcionando

**Comment by Theblood** [comment]
Hola,

Lamentablemente, hemos tenido que suspender temporalmente el proyecto debido a la falta de donaciones para mantenerlo en funcionamiento. Sentimos mucho las molestias que esto pueda causar. Estamos trabajando en buscar nuevas formas de financiamiento para poder volver lo más pronto posible. Agradecemos tu interés en nuestro proyecto y esperamos que tengas un buen fin de semana.
