### ISSUE TITLE
Te cagaste que tuviste que cerrar la pagina

### ISSUE THREAD

**Issue by danieldumma** [Theblood/Celuzador#4]
Hablando de etica y cerraste la pagina jajajaja payaso

**Comment by Theblood** [comment]
Hola @danieldumma 

Entendemos tus inquietudes y te agradecemos por expresarlas. Cerrar el proyecto fue una decisión difícil que tomamos debido a la falta de recursos para mantenerlo en funcionamiento. Estamos comprometidos con la ética y la calidad de la información, y la suspensión temporal del proyecto es parte de nuestro esfuerzo por garantizar que podamos ofrecer contenido de calidad en el futuro.

Lamentamos si esto te ha causado alguna molestia y esperamos poder regresar pronto, mejorando nuestra propuesta y manteniendo los estándares éticos que defendemos. Apreciamos tus comentarios y te deseamos un buen fin de semana.
